<?php 
$bodyClass = 'client';
$pageTitle = ' | Client Project';
include ('header.php'); 
?>
    <main id="content" class="content">
        <article class="project-desc">
            <div class="title">
                <h2>Client Project</h2> </div> <span class="underline"></span>
            <section> <span class="bold tools"> WordPress | HTML | SCSS | jQuery | JavaScript | PHP | Git | Adobe AI | Adobe XD</span>
                <div class="clear"></div>
                <p><span class="bold">Bella Coastal Events | </span>This was a 6 week project where we worked in a team of three to redesign a client’s website. The main goal was to provide information without being overwhelming or too specific and to have a lot of ways to contact/connect with her. Below you can see the original website home page on the top/left versus the new home page on the bottom/right.</p> <a class="button" href="https://brookekaminski.ca/">View Live<span class="screen-reader-text"> internal link to my portfolio home page</span></a> </section>
            <div class="clear"></div>
            <section class="details">
                <div class="cp-desktop">
                    <img src="images/cp-original.jpg" alt="Original front page of client's website">
                    <img src="images/cp-home-1.jpg" alt="New front page of client's website">
                </div>
            </section>
            <section class="details">
                <h3 class="section-titles">Planning</h3>
                <p>After meeting with the client and discussing her goals for the new site, we started with doing wireframes of what each page might have and the overall flow of the site. We later put them into Balasamiq to show the client for an idea. Once we finalized the layout and content we then brought a final mock-up done in Adobe XD.</p> 
                <div class="desktop">
                    <img src="images/cp-wire-1.jpg" alt="Whiteboard wireframe with post-its"> 
                    <img src="images/cp-wire-5.jpg" alt="Balsamiq wireframe">
                    <img src="images/cp-wire-4.jpg" alt="Adobe XD mockup">
                </div>
                </section>
            <section class="details">
                <h3 class="section-titles">Wordpress Development</h3>
                   <p>We wanted to make the website as easy to manage for our client as we could. We created a custom post type so she could upload new testimonials which had custom taxonomy terms so they could be filtered to the correct page. We also removed and customized the dashboard so it was clean and easy to use. Everything is dynamic so that if she decides to add more items, it will be generated by the existing loops.</p>
                    <div class="desktop">
                        <img src="images/cp-code-1.jpg" alt="Wordpress plugin code">
                        <img src="images/cp-code-2.jpg" alt="Wordpress dashboard functions">
                    </div>
            </section>    
                        
            <section class="details">
                <h3 class="section-titles">Mobile View / Navigation</h3>
                <p>We started mobile first and of course the mobile version is very important to our client. She didn't want there to be too much information to scroll through and the pictures to be reasonably sized. The client wanted a simple drop down and we ensured that it stayed accessible.</p>
                <div class="mobile">
                    <picture> <img src="images/cp-mobile-1.jpg" alt="Mobile view of portfolio front page version 1"> </picture>
                    <picture> <img src="images/cp-mobile-2.jpg" alt="Mobile view of portfolio front page version 2"> </picture>
                </div>
            </section>
            <section class="details">
                <h3 class="section-titles">End Result</h3>
                <p>We ended up with a website that is simple and easy to maintain for our client. We ensured there is more focus on images/examples of her work than having it be heavy with text. We also made sure there were plenty of ways to contact her and connect through social media.</p>
                <div class="desktop"> <img src="images/cp-new.jpg" alt="New wedding page, view of top">
                <img src="images/cp-new-2.jpg" alt="New wedding page, view of bottom"> </div>
            </section>
            <section class="details">
                <h3 class="section-titles">Site Testing / SEO / Security</h3>
                <p>We did site testing with a small group of people on the functionality and design of the site.</p>
            </section>
        </article>
        <div class="next-prev"> <a href="landing-page.php">Previous Project</a> <a href="portfolio.php">Next Project</a> </div>
    </main>
    <?php 

include 'footer.php';

?>